import type { IPatients, IPatient, IAttendance, IAgenda } from "../types/globas";

export const mockPatients: IPatients[] = [
  { name: "Maria Silva", id: "1", phone: "(11) 91234-5678", priority: "3", status: "T" },
  { name: "João Souza", id: "2", phone: "(11) 99876-5432", priority: "2", status: "A" },
  { name: "Ana Paula Lima", id: "3", phone: "(11) 91111-2222", priority: "1", status: "N" },
  { name: "Carlos Eduardo Dias", id: "4", phone: "(11) 92222-3333", priority: "2", status: "A" },
  { name: "Beatriz Souza", id: "5", phone: "(11) 93333-4444", priority: "3", status: "T" },
  { name: "Fernanda Alves", id: "6", phone: "(11) 94444-5555", priority: "1", status: "A" },
  { name: "Larissa Oliveira", id: "7", phone: "(11) 95555-6666", priority: "3", status: "N" },
  { name: "Otávio Pires", id: "8", phone: "(11) 96666-7777", priority: "2", status: "T" },
  { name: "Sabrina Lopes", id: "9", phone: "(11) 97777-8888", priority: "1", status: "A" },
  { name: "Vitor Hugo", id: "10", phone: "(11) 98888-9999", priority: "3", status: "F" },
  { name: "Wesley Cardoso", id: "11", phone: "(11) 90000-1111", priority: "2", status: "A" },
  { name: "Juliana Mendes", id: "12", phone: "(11) 91111-2223", priority: "1", status: "T" },
  { name: "Kleber Nunes", id: "13", phone: "(11) 92222-3334", priority: "3", status: "A" },
  { name: "Marcos Vinícius", id: "14", phone: "(11) 93333-4445", priority: "2", status: "N" },
  { name: "Natália Rocha", id: "15", phone: "(11) 94444-5556", priority: "1", status: "A" },
  { name: "Patrícia Silva", id: "16", phone: "(11) 95555-6667", priority: "3", status: "T" },
  { name: "Rafael Teixeira", id: "17", phone: "(11) 96666-7778", priority: "2", status: "A" },
  { name: "Tiago Moreira", id: "18", phone: "(11) 97777-8889", priority: "1", status: "F" },
  { name: "Ursula Barros", id: "19", phone: "(11) 98888-9990", priority: "3", status: "A" },
  { name: "Xuxa Meneghel", id: "20", phone: "(11) 90000-1112", priority: "2", status: "T" },
  { name: "Daniela Castro", id: "21", phone: "(11) 91111-2224", priority: "1", status: "A" },
  { name: "Eduardo Ramos", id: "22", phone: "(11) 92222-3335", priority: "3", status: "N" },
  { name: "Gabriel Martins", id: "23", phone: "(11) 93333-4446", priority: "2", status: "A" },
  { name: "Helena Costa", id: "24", phone: "(11) 94444-5557", priority: "1", status: "T" },
  { name: "Igor Ferreira", id: "25", phone: "(11) 95555-6668", priority: "3", status: "A" },
  { name: "Juliana Costa", id: "26", phone: "(11) 96666-7779", priority: "2", status: "F" },
  { name: "Gustavo Lima", id: "27", phone: "(11) 97777-8890", priority: "1", status: "A" },
  { name: "Marcos Paulo", id: "28", phone: "(11) 98888-9991", priority: "3", status: "T" },
];

export const mockAttendance: IAttendance[] = [
  {
    date: new Date("2025-08-07"),
    spiritual: {
      scheduled: [
        { name: "Maria Silva", priority: "3" },
        { name: "João Souza", priority: "2" },
        { name: "Ana Paula Lima", priority: "1" },
        { name: "Carlos Eduardo Dias", priority: "2" },
        { name: "Beatriz Souza", priority: "3" },
        { name: "Fernanda Alves", priority: "1"},
      ],
      checkedIn: [],
      onGoing: [],
      completed: [],
    },
    lightBath: {
      scheduled: [
        { name: "Larissa Oliveira", priority: "3" },
        { name: "João Souza", priority: "2" },
        { name: "Otávio Pires", priority: "2" },
        { name: "Sabrina Lopes", priority: "1"},
        { name: "Vitor Hugo", priority: "3"},
        { name: "Fernanda Alves", priority: "1"},
        { name: "Wesley Cardoso", priority: "2"},
      ],
      checkedIn: [],
      onGoing: [],
      completed: [],
    },
  },
  {
    date: new Date("2025-08-14"),
    spiritual: {
      scheduled: [
        { name: "Juliana Mendes", priority: "1" },
        { name: "Kleber Nunes", priority: "3" },
        { name: "Marcos Vinícius", priority: "2"},
        { name: "Natália Rocha", priority: "1"},
        { name: "Patrícia Silva", priority: "3"},
      ],
      checkedIn: [],
      onGoing: [],
      completed: [],
    },
    lightBath: {
      scheduled: [
        { name: "Rafael Teixeira", priority: "2" },
        { name: "Tiago Moreira", priority: "1" },
        { name: "Ursula Barros", priority: "3"},
        { name: "Xuxa Meneghel", priority: "2"},
        { name: "Daniela Castro", priority: "1"},
      ],
      checkedIn: [],
      onGoing: [],
      completed: [],
    },
  },
  {
    date: new Date("2025-08-21"),
    spiritual: {
      scheduled: [
        { name: "Eduardo Ramos", priority: "3" },
        { name: "Gabriel Martins", priority: "2" },
        { name: "Helena Costa", priority: "1"},
        { name: "Igor Ferreira", priority: "3"},
        { name: "Juliana Mendes", priority: "1"},
      ],
      checkedIn: [],
      onGoing: [],
      completed: [],
    },
    lightBath: {
      scheduled: [
        { name: "Kleber Nunes", priority: "3" },
        { name: "Marcos Vinícius", priority: "2" },
        { name: "Natália Rocha", priority: "1"},
        { name: "Patrícia Silva", priority: "3"},
        { name: "Rafael Teixeira", priority: "2"},
      ],
      checkedIn: [],
      onGoing: [],
      completed: [],
    },
  },
];

export const mockAgenda: IAgenda = {
  spiritual: [{
    date: new Date("2025-08-07"),
    patients: [
      { id: "1", name: "Maria Silva", priority: "3" },
      { id: "3", name: "Ana Paula Lima", priority: "1" },
      { id: "5", name: "Beatriz Souza", priority: "3" },
      { id: "7", name: "Larissa Oliveira", priority: "3" },
      { id: "11", name: "Wesley Cardoso", priority: "2" },
      { id: "13", name: "Kleber Nunes", priority: "3" },
      { id: "15", name: "Natália Rocha", priority: "1" },
      { id: "19", name: "Ursula Barros", priority: "3" },
    ],
  },
  {
    date: new Date("2025-08-14"),
    patients: [
      { id: "1", name: "Maria Silva", priority: "3" },
      { id: "2", name: "João Souza", priority: "2" },
      { id: "4", name: "Carlos Eduardo Dias", priority: "2" },
      { id: "5", name: "Beatriz Souza", priority: "3" },
      { id: "6", name: "Fernanda Alves", priority: "1" },
      { id: "8", name: "Otávio Pires", priority: "2" },
      { id: "9", name: "Sabrina Lopes", priority: "1" },
      { id: "10", name: "Vitor Hugo", priority: "3" },
    ]
  },
  {
    date: new Date("2025-08-21"),
    patients: [
      { id: "11", name: "Fernanda Lima", priority: "2" },
      { id: "13", name: "Juliana Costa", priority: "1" },
      { id: "15", name: "Marcos Paulo", priority: "3" },
      { id: "17", name: "Gustavo Lima", priority: "1" },
      { id: "19", name: "Patrícia Silva", priority: "2" },
    ],
  }],
  lightBath: [{
    date: new Date("2025-08-07"),
    patients: [
      { id: "2", name: "João Souza", priority: "2" },
      { id: "4", name: "Carlos Eduardo Dias", priority: "2" },
      { id: "6", name: "Fernanda Alves", priority: "1" },
      { id: "8", name: "Otávio Pires", priority: "2" },
      { id: "10", name: "Vitor Hugo", priority: "3" },
      { id: "12", name: "Juliana Mendes", priority: "1" },
    ],
  },
  {
    date: new Date("2025-08-14"),
    patients: [
      { id: "2", name: "João Souza", priority: "2" },
      { id: "3", name: "Ana Paula Lima", priority: "1" },
      { id: "5", name: "Beatriz Souza", priority: "3" },
      { id: "7", name: "Larissa Oliveira", priority: "3" },
      { id: "9", name: "Sabrina Lopes", priority: "1" },
      { id: "11", name: "Wesley Cardoso", priority: "2" },
      { id: "13", name: "Kleber Nunes", priority: "3" },
      { id: "15", name: "Natália Rocha", priority: "1" },
    ],
  },
  {
    date: new Date("2025-08-21"),
    patients: [
      { id: "12", name: "Juliana Mendes", priority: "1" },
      { id: "14", name: "Marcos Vinícius", priority: "2" },
      { id: "16", name: "Patrícia Silva", priority: "3" },
      { id: "17", name: "Rafael Teixeira", priority: "2" },
      { id: "18", name: "Tiago Moreira", priority: "1" },
    ],
  }],
};

export const mockPatient_1: IPatient = {
  id: "1",
  name: "Maria Silva",
  phone: "(11) 91234-5678",
  priority: "3",
  status: "T",
  birthDate: new Date("1980-05-10"),
  mainComplaint: "Dor de cabeça",
  startDate: new Date("2024-06-01"),
  dischargeDate: new Date("2024-06-15"),
  nextAttendanceDates: [
    { date: new Date("2025-08-07"), type: "spiritual" },
  ],
  currentRecommendations: {
    date: new Date("2025-07-08"),
    food: "Frutas",
    water: "Água",
    ointment: "Pomada X",
    lightBath: true,
    rod: false,
    spiritualTreatment: true,
    returnWeeks: 2,
  },
  previousAttendances: [
    {
      attendanceId: "1",
      date: new Date("2025-07-08"),
      notes: "Atendimento anterior.",
      type: "spiritual",
      recommendations: {
        food: "Frutas",
        water: "Água",
        ointment: "Pomada X",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
    {
      attendanceId: "1",
      date: new Date("2025-07-24"),
      notes: "Atendimento anterior.",
      type: "spiritual",
      recommendations: {
        food: "Frutas",
        water: "Água",
        ointment: "Pomada X",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
    {
      attendanceId: "5",
      date: new Date("2025-07-10"),
      notes: "Atendimento anterior.",
      type: "spiritual",
      recommendations: {
        food: "Frutas",
        water: "Água",
        ointment: "Pomada X",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
  ],
};

export const mockPatient_2: IPatient = {
  id: "2",
  name: "João Souza",
  phone: "(11) 99876-5432",
  priority: "2",
  status: "A",
  birthDate: new Date("1975-03-22"),
  mainComplaint: "Dores nas costas",
  startDate: new Date("2024-05-10"),
  dischargeDate: new Date("2024-06-20"),
  nextAttendanceDates: [
    { date: new Date("2025-08-07"), type: "lightBath" },
  ],
  currentRecommendations: {
    date: new Date("2025-07-10"),
    food: "Legumes",
    water: "Água",
    ointment: "Pomada Y",
    lightBath: true,
    rod: true,
    spiritualTreatment: false,
    returnWeeks: 3,
  },
  previousAttendances: [
    {
      attendanceId: "2",
      date: new Date("2025-07-10"),
      notes: "Atendimento anterior.",
      type: "lightBath",
      recommendations: {
        food: "Legumes",
        water: "Água",
        ointment: "Pomada Y",
        lightBath: true,
        rod: true,
        spiritualTreatment: false,
        returnWeeks: 3,
      },
    },
    {
      attendanceId: "2",
      date: new Date("2025-07-24"),
      notes: "Atendimento anterior.",
      type: "lightBath",
      recommendations: {
        food: "Legumes",
        water: "Água",
        ointment: "Pomada Y",
        lightBath: true,
        rod: true,
        spiritualTreatment: false,
        returnWeeks: 3,
      },
    },
  ],
};

export const mockPatient_3: IPatient = {
  id: "3",
  name: "Ana Paula Lima",
  phone: "(11) 91111-2222",
  priority: "1",
  status: "N",
  birthDate: new Date("1990-08-15"),
  mainComplaint: "Ansiedade",
  startDate: new Date("2025-06-01"),
  dischargeDate: null,
  nextAttendanceDates: [
    { date: new Date("2025-08-07"), type: "spiritual" },
  ],
  currentRecommendations: {
    date: new Date("2025-07-10"),
    food: "Frutas",
    water: "Água",
    ointment: "Pomada X",
    lightBath: true,
    rod: false,
    spiritualTreatment: true,
    returnWeeks: 2,
  },
  previousAttendances: [
    {
      attendanceId: "3",
      date: new Date("2025-07-10"),
      notes: "Atendimento anterior.",
      type: "spiritual",
      recommendations: {
        food: "Frutas",
        water: "Água",
        ointment: "Pomada X",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
    {
      attendanceId: "3",
      date: new Date("2025-07-31"),
      notes: "Atendimento anterior.",
      type: "spiritual",
      recommendations: {
        food: "Frutas",
        water: "Água",
        ointment: "Pomada X",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
  ],
};

export const mockPatient_4: IPatient = {
  id: "4",
  name: "Carlos Eduardo Dias",
  phone: "(11) 92222-3333",
  priority: "2",
  status: "A",
  birthDate: new Date("1982-12-03"),
  mainComplaint: "Insônia",
  startDate: new Date("2025-05-20"),
  dischargeDate: new Date("2025-07-01"),
  nextAttendanceDates: [
    { date: new Date("2025-08-07"), type: "lightBath" },
  ],
  currentRecommendations: {
    date: new Date("2025-07-10"),
    food: "Legumes",
    water: "Água",
    ointment: "Pomada Y",
    lightBath: true,
    rod: true,
    spiritualTreatment: false,
    returnWeeks: 3,
  },
  previousAttendances: [
    {
      attendanceId: "4",
      date: new Date("2025-07-10"),
      notes: "Atendimento anterior.",
      type: "lightBath",
      recommendations: {
        food: "Legumes",
        water: "Água",
        ointment: "Pomada Y",
        lightBath: true,
        rod: true,
        spiritualTreatment: false,
        returnWeeks: 3,
      },
    },
    {
      attendanceId: "4",
      date: new Date("2025-07-31"),
      notes: "Atendimento anterior.",
      type: "lightBath",
      recommendations: {
        food: "Legumes",
        water: "Água",
        ointment: "Pomada Y",
        lightBath: true,
        rod: true,
        spiritualTreatment: false,
        returnWeeks: 3,
      },
    },
  ],
};

export const mockPatient_5: IPatient = {
  id: "5",
  name: "Beatriz Souza",
  phone: "(11) 93333-4444",
  priority: "3",
  status: "T",
  birthDate: new Date("1995-11-21"),
  mainComplaint: "Estresse",
  startDate: new Date("2025-06-10"),
  dischargeDate: null,
  nextAttendanceDates: [
    { date: new Date("2025-08-07"), type: "spiritual" },
  ],
  currentRecommendations: {
    date: new Date("2025-07-17"),
    food: "Frutas",
    water: "Água",
    ointment: "Pomada X",
    lightBath: true,
    rod: false,
    spiritualTreatment: true,
    returnWeeks: 2,
  },
  previousAttendances: [
    {
      attendanceId: "5",
      date: new Date("2025-07-17"),
      notes: "Atendimento anterior.",
      type: "spiritual",
      recommendations: {
        food: "Frutas",
        water: "Água",
        ointment: "Pomada X",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
    {
      attendanceId: "5",
      date: new Date("2025-07-10"),
      notes: "Atendimento anterior.",
      type: "spiritual",
      recommendations: {
        food: "Frutas",
        water: "Água",
        ointment: "Pomada X",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
  ],
};
