import { Patient } from "@/types/patient";
import { AgendaItem } from "@/types/agenda";
import { Attendance } from "@/types/attendance";

export const mockPatients: Patient[] = [
  {
    id: "1",
    registrationNumber: 1,
    name: "Maria Silva",
    birthDate: "1980-05-10",
    phone: "(11) 91234-5678",
    priority: "N",
    mainComplaint: "Dor de cabeça",
    status: "T",
    spiritualConsultation: {
      startDate: "2024-06-01",
      nextDate: "2024-06-15",
      dischargeDate: "",
      recommendations: {
        food: "Frutas e legumes",
        water: "Beber 2L/dia",
        ointment: "Pomada X",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [
      {
        date: "2025-06-01",
        status: "OK",
        notes: "Paciente relatou melhora significativa.",
        recommendations: {
          food: "Frutas e legumes",
          water: "Beber 2L/dia",
          ointment: "Pomada X",
          lightBath: true,
          rod: false,
          spiritualTreatment: true,
          returnWeeks: 2,
        },
      },
      {
        date: "2025-06-15",
        status: "OK",
        notes: "Sem queixas. Manter recomendações.",
        recommendations: {
          food: "Frutas e legumes",
          water: "Beber 2L/dia",
          ointment: "Pomada X",
          lightBath: true,
          rod: false,
          spiritualTreatment: true,
          returnWeeks: 2,
        },
      },
    ],
    history: [],
  },
  {
    id: "2",
    registrationNumber: 2,
    name: "João Souza",
    birthDate: "1975-03-22",
    phone: "(11) 99876-5432",
    priority: "I",
    mainComplaint: "Dores nas costas",
    status: "A",
    spiritualConsultation: {
      startDate: "2024-05-10",
      nextDate: "2024-06-10",
      dischargeDate: "2024-06-20",
      recommendations: {
        food: "Evitar frituras",
        water: "Beber 1.5L/dia",
        ointment: "Pomada Y",
        lightBath: false,
        rod: true,
        spiritualTreatment: false,
        returnWeeks: 4,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  // Pacientes adicionais para testes
  {
    id: "3",
    registrationNumber: 3,
    name: "Ana Paula Lima",
    birthDate: "1990-08-15",
    phone: "(11) 91111-2222",
    priority: "E",
    mainComplaint: "Ansiedade",
    status: "N",
    spiritualConsultation: {
      startDate: "2025-06-01",
      nextDate: "2025-06-15",
      dischargeDate: "",
      recommendations: {
        food: "Vegetais",
        water: "Beber 2L/dia",
        ointment: "Pomada Z",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "4",
    registrationNumber: 4,
    name: "Carlos Eduardo Dias",
    birthDate: "1982-12-03",
    phone: "(11) 92222-3333",
    priority: "I",
    mainComplaint: "Insônia",
    status: "A",
    spiritualConsultation: {
      startDate: "2025-05-20",
      nextDate: "2025-06-20",
      dischargeDate: "2025-07-01",
      recommendations: {
        food: "Frutas",
        water: "Beber 1.8L/dia",
        ointment: "Pomada X",
        lightBath: false,
        rod: true,
        spiritualTreatment: false,
        returnWeeks: 3,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "5",
    registrationNumber: 5,
    name: "Beatriz Souza",
    birthDate: "1995-11-21",
    phone: "(11) 93333-4444",
    priority: "N",
    mainComplaint: "Estresse",
    status: "T",
    spiritualConsultation: {
      startDate: "2025-06-10",
      nextDate: "2025-06-24",
      dischargeDate: "",
      recommendations: {
        food: "Saladas",
        water: "Beber 2.2L/dia",
        ointment: "Pomada Y",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "6",
    registrationNumber: 6,
    name: "Daniela Castro",
    birthDate: "1988-04-17",
    phone: "(11) 94444-5555",
    priority: "E",
    mainComplaint: "Fadiga",
    status: "F",
    spiritualConsultation: {
      startDate: "2025-04-01",
      nextDate: "2025-04-15",
      dischargeDate: "2025-05-01",
      recommendations: {
        food: "Legumes",
        water: "Beber 2L/dia",
        ointment: "Pomada Z",
        lightBath: false,
        rod: true,
        spiritualTreatment: false,
        returnWeeks: 4,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "7",
    registrationNumber: 7,
    name: "Eduardo Ramos",
    birthDate: "1979-09-30",
    phone: "(11) 95555-6666",
    priority: "I",
    mainComplaint: "Dores musculares",
    status: "A",
    spiritualConsultation: {
      startDate: "2025-05-05",
      nextDate: "2025-05-19",
      dischargeDate: "2025-06-01",
      recommendations: {
        food: "Frutas",
        water: "Beber 1.7L/dia",
        ointment: "Pomada X",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "8",
    registrationNumber: 8,
    name: "Fernanda Alves",
    birthDate: "1992-07-12",
    phone: "(11) 96666-7777",
    priority: "N",
    mainComplaint: "Enxaqueca",
    status: "T",
    spiritualConsultation: {
      startDate: "2025-06-12",
      nextDate: "2025-06-26",
      dischargeDate: "",
      recommendations: {
        food: "Verduras",
        water: "Beber 2.1L/dia",
        ointment: "Pomada Y",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "9",
    registrationNumber: 9,
    name: "Gabriel Martins",
    birthDate: "1985-02-28",
    phone: "(11) 97777-8888",
    priority: "E",
    mainComplaint: "Alergia",
    status: "N",
    spiritualConsultation: {
      startDate: "2025-06-15",
      nextDate: "2025-06-29",
      dischargeDate: "",
      recommendations: {
        food: "Frutas",
        water: "Beber 2L/dia",
        ointment: "Pomada Z",
        lightBath: false,
        rod: true,
        spiritualTreatment: false,
        returnWeeks: 3,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "10",
    registrationNumber: 10,
    name: "Helena Costa",
    birthDate: "1998-10-05",
    phone: "(11) 98888-9999",
    priority: "I",
    mainComplaint: "Problemas digestivos",
    status: "A",
    spiritualConsultation: {
      startDate: "2025-05-25",
      nextDate: "2025-06-08",
      dischargeDate: "2025-06-20",
      recommendations: {
        food: "Legumes",
        water: "Beber 1.9L/dia",
        ointment: "Pomada X",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "11",
    registrationNumber: 11,
    name: "Igor Ferreira",
    birthDate: "1983-06-18",
    phone: "(11) 99999-0000",
    priority: "N",
    mainComplaint: "Cansaço",
    status: "T",
    spiritualConsultation: {
      startDate: "2025-06-18",
      nextDate: "2025-07-02",
      dischargeDate: "",
      recommendations: {
        food: "Saladas",
        water: "Beber 2.3L/dia",
        ointment: "Pomada Y",
        lightBath: false,
        rod: true,
        spiritualTreatment: false,
        returnWeeks: 2,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "12",
    registrationNumber: 12,
    name: "Juliana Mendes",
    birthDate: "1991-01-23",
    phone: "(11) 90000-1111",
    priority: "E",
    mainComplaint: "Dores nas pernas",
    status: "F",
    spiritualConsultation: {
      startDate: "2025-04-10",
      nextDate: "2025-04-24",
      dischargeDate: "2025-05-10",
      recommendations: {
        food: "Frutas",
        water: "Beber 2L/dia",
        ointment: "Pomada Z",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 4,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "13",
    registrationNumber: 13,
    name: "Kleber Nunes",
    birthDate: "1987-03-14",
    phone: "(11) 91112-1314",
    priority: "I",
    mainComplaint: "Problemas respiratórios",
    status: "A",
    spiritualConsultation: {
      startDate: "2025-05-15",
      nextDate: "2025-05-29",
      dischargeDate: "2025-06-12",
      recommendations: {
        food: "Verduras",
        water: "Beber 1.6L/dia",
        ointment: "Pomada X",
        lightBath: false,
        rod: true,
        spiritualTreatment: false,
        returnWeeks: 3,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "14",
    registrationNumber: 14,
    name: "Larissa Oliveira",
    birthDate: "1993-05-27",
    phone: "(11) 92223-2425",
    priority: "N",
    mainComplaint: "Dores de cabeça",
    status: "T",
    spiritualConsultation: {
      startDate: "2025-06-20",
      nextDate: "2025-07-04",
      dischargeDate: "",
      recommendations: {
        food: "Frutas",
        water: "Beber 2L/dia",
        ointment: "Pomada Y",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "15",
    registrationNumber: 15,
    name: "Marcos Vinícius",
    birthDate: "1986-08-09",
    phone: "(11) 93334-3536",
    priority: "E",
    mainComplaint: "Problemas de coluna",
    status: "N",
    spiritualConsultation: {
      startDate: "2025-06-22",
      nextDate: "2025-07-06",
      dischargeDate: "",
      recommendations: {
        food: "Legumes",
        water: "Beber 2.2L/dia",
        ointment: "Pomada Z",
        lightBath: false,
        rod: true,
        spiritualTreatment: false,
        returnWeeks: 2,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "16",
    registrationNumber: 16,
    name: "Natália Rocha",
    birthDate: "1997-12-11",
    phone: "(11) 94445-4647",
    priority: "I",
    mainComplaint: "Dores lombares",
    status: "A",
    spiritualConsultation: {
      startDate: "2025-05-30",
      nextDate: "2025-06-13",
      dischargeDate: "2025-06-27",
      recommendations: {
        food: "Saladas",
        water: "Beber 1.8L/dia",
        ointment: "Pomada X",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "17",
    registrationNumber: 17,
    name: "Otávio Pires",
    birthDate: "1984-07-19",
    phone: "(11) 95556-5758",
    priority: "N",
    mainComplaint: "Dores abdominais",
    status: "T",
    spiritualConsultation: {
      startDate: "2025-06-25",
      nextDate: "2025-07-09",
      dischargeDate: "",
      recommendations: {
        food: "Verduras",
        water: "Beber 2.1L/dia",
        ointment: "Pomada Y",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "18",
    registrationNumber: 18,
    name: "Patrícia Silva",
    birthDate: "1996-03-22",
    phone: "(11) 96667-6869",
    priority: "E",
    mainComplaint: "Dores no joelho",
    status: "N",
    spiritualConsultation: {
      startDate: "2025-06-28",
      nextDate: "2025-07-12",
      dischargeDate: "",
      recommendations: {
        food: "Frutas",
        water: "Beber 2L/dia",
        ointment: "Pomada Z",
        lightBath: false,
        rod: true,
        spiritualTreatment: false,
        returnWeeks: 3,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "19",
    registrationNumber: 19,
    name: "Rafael Teixeira",
    birthDate: "1981-11-02",
    phone: "(11) 97778-7970",
    priority: "I",
    mainComplaint: "Dores no ombro",
    status: "A",
    spiritualConsultation: {
      startDate: "2025-05-12",
      nextDate: "2025-05-26",
      dischargeDate: "2025-06-09",
      recommendations: {
        food: "Legumes",
        water: "Beber 1.7L/dia",
        ointment: "Pomada X",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "20",
    registrationNumber: 20,
    name: "Sabrina Lopes",
    birthDate: "1994-09-16",
    phone: "(11) 98889-8081",
    priority: "N",
    mainComplaint: "Dores nas costas",
    status: "T",
    spiritualConsultation: {
      startDate: "2025-06-30",
      nextDate: "2025-07-14",
      dischargeDate: "",
      recommendations: {
        food: "Saladas",
        water: "Beber 2.2L/dia",
        ointment: "Pomada Y",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "21",
    registrationNumber: 21,
    name: "Tiago Moreira",
    birthDate: "1989-02-07",
    phone: "(11) 90001-9192",
    priority: "E",
    mainComplaint: "Dores no pescoço",
    status: "F",
    spiritualConsultation: {
      startDate: "2025-04-15",
      nextDate: "2025-04-29",
      dischargeDate: "2025-05-13",
      recommendations: {
        food: "Frutas",
        water: "Beber 2L/dia",
        ointment: "Pomada Z",
        lightBath: false,
        rod: true,
        spiritualTreatment: false,
        returnWeeks: 4,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "22",
    registrationNumber: 22,
    name: "Ursula Barros",
    birthDate: "1999-06-30",
    phone: "(11) 91113-2324",
    priority: "I",
    mainComplaint: "Dores de cabeça",
    status: "A",
    spiritualConsultation: {
      startDate: "2025-05-18",
      nextDate: "2025-06-01",
      dischargeDate: "2025-06-15",
      recommendations: {
        food: "Verduras",
        water: "Beber 1.8L/dia",
        ointment: "Pomada X",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "23",
    registrationNumber: 23,
    name: "Vitor Hugo",
    birthDate: "1980-10-13",
    phone: "(11) 92224-2526",
    priority: "N",
    mainComplaint: "Dores nas costas",
    status: "T",
    spiritualConsultation: {
      startDate: "2025-07-01",
      nextDate: "2025-07-15",
      dischargeDate: "",
      recommendations: {
        food: "Frutas",
        water: "Beber 2L/dia",
        ointment: "Pomada Y",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "24",
    registrationNumber: 24,
    name: "Wesley Cardoso",
    birthDate: "1985-12-25",
    phone: "(11) 93335-3637",
    priority: "E",
    mainComplaint: "Dores musculares",
    status: "N",
    spiritualConsultation: {
      startDate: "2025-07-03",
      nextDate: "2025-07-17",
      dischargeDate: "",
      recommendations: {
        food: "Legumes",
        water: "Beber 2.2L/dia",
        ointment: "Pomada Z",
        lightBath: false,
        rod: true,
        spiritualTreatment: false,
        returnWeeks: 2,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
  {
    id: "25",
    registrationNumber: 25,
    name: "Xuxa Meneghel",
    birthDate: "1963-03-27",
    phone: "(11) 94446-4748",
    priority: "I",
    mainComplaint: "Dores nas costas",
    status: "A",
    spiritualConsultation: {
      startDate: "2025-05-22",
      nextDate: "2025-06-05",
      dischargeDate: "2025-06-19",
      recommendations: {
        food: "Saladas",
        water: "Beber 1.9L/dia",
        ointment: "Pomada X",
        lightBath: true,
        rod: false,
        spiritualTreatment: true,
        returnWeeks: 2,
      },
    },
    lightBaths: [],
    rods: [],
    attendances: [],
    history: [],
  },
];

export const mockAgenda: AgendaItem[] = [
  {
    date: "2025-07-01",
    type: "spiritual",
    patients: [
      "Maria Silva",
      "João Souza",
      "Ana Paula Lima",
      "Carlos Eduardo Dias",
      "Beatriz Souza",
      "Daniela Castro",
      "Eduardo Ramos",
      "Fernanda Alves",
      "Gabriel Martins",
      "Helena Costa",
      "Igor Ferreira",
    ],
  },
  {
    date: "2025-07-01",
    type: "lightBath",
    patients: [
      "Maria Silva",
      "Beatriz Souza",
      "Fernanda Alves",
      "Larissa Oliveira",
      "Otávio Pires",
      "Sabrina Lopes",
      "Vitor Hugo",
      "Wesley Cardoso",
    ],
  },
  {
    date: "2025-07-08",
    type: "spiritual",
    patients: [
      "Juliana Mendes",
      "Kleber Nunes",
      "Larissa Oliveira",
      "Marcos Vinícius",
      "Natália Rocha",
      "Patrícia Silva",
      "Rafael Teixeira",
      "Tiago Moreira",
      "Ursula Barros",
      "Xuxa Meneghel",
    ],
  },
  {
    date: "2025-07-08",
    type: "lightBath",
    patients: [
      "Ana Paula Lima",
      "Gabriel Martins",
      "Helena Costa",
      "Juliana Mendes",
      "Patrícia Silva",
      "Tiago Moreira",
      "Ursula Barros",
    ],
  },
];

export const mockAttendance: Attendance[] = [
  {
    date: "2025-07-01",
    type: "spiritual",
    patients: [
      "Maria Silva",
      "João Souza",
      "Ana Paula Lima",
      "Carlos Eduardo Dias",
      "Beatriz Souza",
    ],
  },
  {
    date: "2025-07-01",
    type: "lightBath",
    patients: [
      "Maria Silva",
      "Beatriz Souza",
      "Fernanda Alves",
      "Larissa Oliveira",
    ],
  },
  {
    date: "2025-07-08",
    type: "spiritual",
    patients: [
      "Juliana Mendes",
      "Kleber Nunes",
      "Larissa Oliveira",
      "Marcos Vinícius",
    ],
  },
  {
    date: "2025-07-08",
    type: "lightBath",
    patients: [
      "Ana Paula Lima",
      "Gabriel Martins",
      "Helena Costa",
    ],
  },
];
