import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TabNav from "@/components/common/TabNav";
import { TopNavigation } from "@/components/layout/TopNavigation";
import { TimezoneProvider } from "@/contexts/TimezoneContext";
import { PatientsProvider } from "@/contexts/PatientsContext";
import { AttendancesProvider } from "@/contexts/AttendancesContext";
import { AgendaProvider } from "@/contexts/AgendaContext";
import { TreatmentRecordsProvider } from "@/contexts/TreatmentRecordsContext";
import { QueryProvider } from "@/providers/QueryProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${inter.variable} antialiased bg-[color:var(--background)] text-[color:var(--foreground)]`}
      >
        <QueryProvider>
          <TimezoneProvider>
            <PatientsProvider>
              <AttendancesProvider>
                <AgendaProvider>
                  <TreatmentRecordsProvider>
                    <TopNavigation />
                    <TabNav />
                    <main className="w-full min-h-screen p-4 max-w-[1200px] mx-auto">
                      {children}
                    </main>
                  </TreatmentRecordsProvider>
                </AgendaProvider>
              </AttendancesProvider>
            </PatientsProvider>
          </TimezoneProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
